language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
    # There is a problem in fraday 0.8 with jruby + ssl
    - rvm: jruby-19mode
rvm:
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
notifications:
  email:
    - daniel@securityroots.com
